
CREATE DATABASE LINK DblinkSiedziba
CONNECT TO SIEDZIBA IDENTIFIED BY "Qead36a!"
USING 'MAIN';

CREATE SYNONYM Umowy FOR Umowy@DblinkSiedziba;


CREATE MATERIALIZED VIEW mv_aktualne_kursy
BUILD IMMEDIATE
REFRESH COMPLETE
START WITH SYSDATE
NEXT SYSDATE + 10
AS
SELECT 
    r.nazwa AS nazwa_kursu,
    r.cena AS cena_kursu,
    COUNT(u.umowa_id) AS ilosc_uczestnikow,
    w.imie AS imie_prowadzacego,
    w.nazwisko AS nazwisko_prowadzacego
FROM kursy@DblinkSiedziba k
JOIN rodzaje@DblinkSiedziba r ON k.rodzaj_id = r.rodzaj_id
LEFT JOIN wykladowcy@DblinkSiedziba w ON k.wykladowca_id = w.wykladowca_id
LEFT JOIN umowy@DblinkSiedziba u ON k.kurs_id = u.kurs_id
GROUP BY k.kurs_id, r.nazwa, r.cena, w.imie, w.nazwisko;

--------------------------------------------------------
--  File created - sobota-maja-30-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View MV_KURSANCI_FILIA_DAY
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "RBDN2_ST2"."MV_KURSANCI_FILIA_DAY" ("KURSANT_ID", "IMIE", "NAZWISKO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH COMPLETE ON DEMAND START WITH sysdate+0 NEXT SYSDATE + 1
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT "KURSANCI"."KURSANT_ID" "KURSANT_ID","KURSANCI"."IMIE" "IMIE","KURSANCI"."NAZWISKO" "NAZWISKO" FROM "KURSANCI"@"DBLINKFILIA" "KURSANCI";
 

   COMMENT ON MATERIALIZED VIEW "RBDN2_ST2"."MV_KURSANCI_FILIA_DAY"  IS 'snapshot table for snapshot RBDN2_ST2.MV_KURSANCI_FILIA_DAY';
REM INSERTING into RBDN2_ST2.MV_KURSANCI_FILIA_DAY
SET DEFINE OFF;
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1000','ANTONI','NOWAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1001','JAN','KOWALSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1002','ALEKSANDER','WIŚNIEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1003','JAKUB','WÓJCIK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1004','FRANCISZEK','KOWALCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1005','SZYMON','KAMIŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1006','FILIP','LEWANDOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1007','MIKOŁAJ','DĄBROWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1008','LEON','ZIELIŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1009','STANISŁAW','SZYMAŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1010','WOJCIECH','WOŹNIAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1011','ADAM','KOZŁOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1012','KACPER','JANKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1013','TYMON','MAZUR');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1014','NIKODEM','WOJCIECHOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1015','MARCEL','KWIATKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1016','IGNACY','KRAWCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1017','MICHAŁ','KACZMAREK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1018','WIKTOR','PIOTROWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1019','IGOR','GRABOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1020','OLIWIER','ZAJĄC');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1021','MAKSYMILIAN','PAWŁOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1022','PIOTR','MICHALSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1023','TYMOTEUSZ','KRÓL');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1024','MIŁOSZ','NOWAKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1025','OSKAR','WIECZOREK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1026','JULIAN','WRÓBEL');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1027','BARTOSZ','JABŁOŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1028','DAWID','ADAMCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1029','MATEUSZ','DUDEK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1030','KRZYSZTOF','MAJEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1031','GABRIEL','NOWICKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1032','KAROL','OLSZEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1033','ALAN','STĘPIEŃ');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1034','DOMINIK','JAWORSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1035','HUBERT','MALINOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1036','TOMASZ','PAWLAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1037','MACIEJ','GÓRSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1038','FABIAN','WITKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1039','BRUNO','SIKORA');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1040','PAWEŁ','WALCZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1041','NATAN','RUTKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1042','KSAWERY','BARAN');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1043','KAMIL','MICHALAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1044','BORYS','SZEWCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1045','BARTŁOMIEJ','OSTROWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1046','ARTUR','TOMASZEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1047','TADEUSZ','PIETRZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1048','PATRYK','ZALEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1049','CEZARY','DUDA');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1050','KAJETAN','WRÓBLEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1051','KUBA','JASIŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1052','ADRIAN','MARCINIAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1053','OLAF','BĄK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1054','HENRYK','SADOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1055','GRZEGORZ','ZAWADZKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1056','SEBASTIAN','JAKUBOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1057','DANIEL','WILK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1058','ERYK','CHMIELEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1059','KORNEL','WŁODARCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1060','KRYSTIAN','BORKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1061','WITOLD','SOKOŁOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1062','KAZIMIERZ','SZCZEPAŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1063','JÓZEF','SAWICKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1064','RAFAŁ','LIS');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1065','TEODOR','KUCHARSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1066','MILAN','MAZUREK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1067','JERZY','KUBIAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1068','STEFAN','KALINOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1069','TOBIASZ','WYSOCKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1070','MIESZKO','MACIEJEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1071','ŁUKASZ','CZARNECKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1072','LEONARD','KOŁODZIEJ');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1073','EMIL','URBAŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1074','GUSTAW','KAŹMIERCZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1075','MARCIN','SOBCZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1076','DAMIAN','KONIECZNY');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1077','OLIVIER','GŁOWACKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1078','ROBERT','WASILEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1079','BŁAŻEJ','ZAKRZEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA_DAY (KURSANT_ID,IMIE,NAZWISKO) values ('1080','KONSTANTY','KRUPA');



--------------------------------------------------------
--  File created - sobota-maja-30-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Materialized View MV_KURSANCI_FILIA
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "RBDN2_ST2"."MV_KURSANCI_FILIA" ("KURSANT_ID", "IMIE", "NAZWISKO")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  REFRESH COMPLETE ON DEMAND
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE QUERY REWRITE
  AS SELECT "KURSANCI"."KURSANT_ID" "KURSANT_ID","KURSANCI"."IMIE" "IMIE","KURSANCI"."NAZWISKO" "NAZWISKO" FROM "KURSANCI"@"DBLINKFILIA" "KURSANCI";
 

   COMMENT ON MATERIALIZED VIEW "RBDN2_ST2"."MV_KURSANCI_FILIA"  IS 'snapshot table for snapshot RBDN2_ST2.MV_KURSANCI_FILIA';
REM INSERTING into RBDN2_ST2.MV_KURSANCI_FILIA
SET DEFINE OFF;
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1000','ANTONI','NOWAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1001','JAN','KOWALSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1002','ALEKSANDER','WIŚNIEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1003','JAKUB','WÓJCIK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1004','FRANCISZEK','KOWALCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1005','SZYMON','KAMIŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1006','FILIP','LEWANDOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1007','MIKOŁAJ','DĄBROWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1008','LEON','ZIELIŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1009','STANISŁAW','SZYMAŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1010','WOJCIECH','WOŹNIAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1011','ADAM','KOZŁOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1012','KACPER','JANKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1013','TYMON','MAZUR');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1014','NIKODEM','WOJCIECHOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1015','MARCEL','KWIATKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1016','IGNACY','KRAWCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1017','MICHAŁ','KACZMAREK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1018','WIKTOR','PIOTROWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1019','IGOR','GRABOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1020','OLIWIER','ZAJĄC');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1021','MAKSYMILIAN','PAWŁOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1022','PIOTR','MICHALSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1023','TYMOTEUSZ','KRÓL');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1024','MIŁOSZ','NOWAKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1025','OSKAR','WIECZOREK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1026','JULIAN','WRÓBEL');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1027','BARTOSZ','JABŁOŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1028','DAWID','ADAMCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1029','MATEUSZ','DUDEK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1030','KRZYSZTOF','MAJEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1031','GABRIEL','NOWICKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1032','KAROL','OLSZEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1033','ALAN','STĘPIEŃ');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1034','DOMINIK','JAWORSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1035','HUBERT','MALINOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1036','TOMASZ','PAWLAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1037','MACIEJ','GÓRSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1038','FABIAN','WITKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1039','BRUNO','SIKORA');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1040','PAWEŁ','WALCZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1041','NATAN','RUTKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1042','KSAWERY','BARAN');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1043','KAMIL','MICHALAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1044','BORYS','SZEWCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1045','BARTŁOMIEJ','OSTROWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1046','ARTUR','TOMASZEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1047','TADEUSZ','PIETRZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1048','PATRYK','ZALEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1049','CEZARY','DUDA');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1050','KAJETAN','WRÓBLEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1051','KUBA','JASIŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1052','ADRIAN','MARCINIAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1053','OLAF','BĄK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1054','HENRYK','SADOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1055','GRZEGORZ','ZAWADZKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1056','SEBASTIAN','JAKUBOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1057','DANIEL','WILK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1058','ERYK','CHMIELEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1059','KORNEL','WŁODARCZYK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1060','KRYSTIAN','BORKOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1061','WITOLD','SOKOŁOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1062','KAZIMIERZ','SZCZEPAŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1063','JÓZEF','SAWICKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1064','RAFAŁ','LIS');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1065','TEODOR','KUCHARSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1066','MILAN','MAZUREK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1067','JERZY','KUBIAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1068','STEFAN','KALINOWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1069','TOBIASZ','WYSOCKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1070','MIESZKO','MACIEJEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1071','ŁUKASZ','CZARNECKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1072','LEONARD','KOŁODZIEJ');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1073','EMIL','URBAŃSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1074','GUSTAW','KAŹMIERCZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1075','MARCIN','SOBCZAK');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1076','DAMIAN','KONIECZNY');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1077','OLIVIER','GŁOWACKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1078','ROBERT','WASILEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1079','BŁAŻEJ','ZAKRZEWSKI');
Insert into RBDN2_ST2.MV_KURSANCI_FILIA (KURSANT_ID,IMIE,NAZWISKO) values ('1080','KONSTANTY','KRUPA');


